apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: gd61cg0zf-python 
  janus-idp.io/tekton: gd61cg0zf-python
  backstage.io/kubernetes-id: gd61cg0zf-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: gd61cg0zf-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml