apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: gd61cg0zf-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: gd61cg0zf-python 
  name: gd61cg0zf-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: gd61cg0zf-python 
